# Generated by Django 6.1.2 on 2026-10-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField(db_index=True, help_text='Unique OPIS Truckstop identifier.', unique=True)),
                ('name', models.CharField(help_text='Truckstop business name.', max_length=255)),
                ('address', models.CharField(help_text='Street or highway exit address.', max_length=255)),
                ('city', models.CharField(db_index=True, max_length=128)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('rack_id', models.IntegerField(blank=True, help_text='Wholesale terminal rack ID.', null=True)),
                ('price_per_gallon', models.DecimalField(decimal_places=4, help_text='Retail diesel price in USD per gallon (lowest available rate).', max_digits=6)),
                ('latitude', models.FloatField(blank=True, help_text='Approximate station latitude in degrees.', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Approximate station longitude in degrees.', null=True)),
                ('coordinate_source', models.CharField(default='city_centroid', help_text="Source / precision level of coordinates ('city_centroid', 'unresolved').", max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['station_id'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='fuel_station_coords_idx'), models.Index(fields=['state', 'city'], name='fuel_station_state_city_idx')],
            },
        ),
    ]
